### ISSUE TITLE
Is the RSS / Atom feed gone ?

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/blog.rust-lang.org#311] opened 2018-12-06 19:02 UTC
# Technical Bug Report
## Your Environment

Not relevant here.

## Is this an issue with Rust, CSS, or HTML (or a combination)?

It looks like a server-side issue, so probably Rust.

## Expected Behavior

There used to be a way to get an RSS / Atom feed of the Rust blog via https://blog.rust-lang.org/feed.xml . This was convenient for aggregating Rust news with other news in a single RSS feed reader like Thunderbird.

## Current Behavior

The URL now errors out with a 404 "not found" error. Is the feature gone?

## Step to Reproduce

    curl https://blog.rust-lang.org/feed.xml

**Comment by HadrienG2** [comment] 2018-12-06 19:09
Ah, sorry, the "send a fix here" link at the bottom of the page brought me to the beta.rust-lang.org repo. Is this the expected behaviour, or should I report another issue about that?

**Comment by wezm** [comment] 2018-12-06 23:59
Dupe of #307?

**Comment by pietroalbini** [comment] 2018-12-08 11:41
Duplicate of https://github.com/rust-lang/blog.rust-lang.org/issues/307

**Closed by pietroalbini** 2018-12-08 11:41 UTC
